//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart.FA.Catalog.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CatalogResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CatalogResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Smart.FA.Catalog.Localization.CatalogResources", typeof(CatalogResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encoder une formation.
        /// </summary>
        public static string AddNewTraining {
            get {
                return ResourceManager.GetString("AddNewTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charte d&apos;utilisation.
        /// </summary>
        public static string AdminHomepage_AcceptCharter {
            get {
                return ResourceManager.GetString("AdminHomepage_AcceptCharter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La charte d&apos;utilisateur de Formateurs Associés n&apos;a pas été acceptée.
        /// </summary>
        public static string AdminHomePage_HasNotAcceptedUserChart {
            get {
                return ResourceManager.GetString("AdminHomePage_HasNotAcceptedUserChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je m&apos;engage à respecter la Charter d&apos;utilisation de Formateurs Associés.
        /// </summary>
        public static string AdminHomepage_IAcceptCharter {
            get {
                return ResourceManager.GetString("AdminHomepage_IAcceptCharter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to learning.smart.coop est un catalogue des formations organisées et produites par Smart au travers des entités Formateurs Associés asbl et accessoirement Productions Associées asbl. C&apos;est un outil en ligne mis à votre disposition gratuitement et sans publicité..
        /// </summary>
        public static string AdminHomepage_IntroductionPart1 {
            get {
                return ResourceManager.GetString("AdminHomepage_IntroductionPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes invité·es à y compléter  votre fiche de profil, puis à y encoder les formations que vous proposez..
        /// </summary>
        public static string AdminHomepage_IntroductionPart2 {
            get {
                return ResourceManager.GetString("AdminHomepage_IntroductionPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les informations ainsi encodées seront visibles publiquement sur le site vitrine learning.smart.coop. .
        /// </summary>
        public static string AdminHomepage_IntroductionPart3 {
            get {
                return ResourceManager.GetString("AdminHomepage_IntroductionPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lire la charte utilisateur.
        /// </summary>
        public static string AdminHomePage_UserChart {
            get {
                return ResourceManager.GetString("AdminHomePage_UserChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface d&apos;encodage de formations.
        /// </summary>
        public static string AdminHomepage_WhatIsFormateurAssocieTitle {
            get {
                return ResourceManager.GetString("AdminHomepage_WhatIsFormateurAssocieTitle", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< Updated upstream
        ///   Looks up a localized string similar to Avant d’encoder des formations, vous devez confirmer avoir lu et accepté les conditions énoncées dans la charte d’utilisation du site learning.smart.coop. Cette charte est également disponible à la consultation dans votre Espace Activité.   .
        /// </summary>
        public static string AdminUserChart_IntroductionPart1 {
            get {
                return ResourceManager.GetString("AdminUserChart_IntroductionPart1", resourceCulture);
=======
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AdminHomepageProfil_IntroductionPart1 {
            get {
                return ResourceManager.GetString("AdminHomepageProfil_IntroductionPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AdminHomepageProfil_IntroductionPart2 {
            get {
                return ResourceManager.GetString("AdminHomepageProfil_IntroductionPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AdminHomepageProfil_Title {
            get {
                return ResourceManager.GetString("AdminHomepageProfil_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AdminHomepageTraining_IntroductionPart1 {
            get {
                return ResourceManager.GetString("AdminHomepageTraining_IntroductionPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AdminHomepageTraining_IntroductionPart2 {
            get {
                return ResourceManager.GetString("AdminHomepageTraining_IntroductionPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AdminHomepageTraining_IntroductionPart3 {
            get {
                return ResourceManager.GetString("AdminHomepageTraining_IntroductionPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AdminHomepageTraining_Title {
            get {
                return ResourceManager.GetString("AdminHomepageTraining_Title", resourceCulture);
>>>>>>> Stashed changes
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Une erreur s&apos;est déroulée durant la recherche. Veuillez essayer à nouveau.
        /// </summary>
        public static string AnErrorOccurredWhileSearching {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Êtes vous sûr-e ?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La biographie ne peut excéder 500 caractères.
        /// </summary>
        public static string BioCannotExceed500Chars {
            get {
                return ResourceManager.GetString("BioCannotExceed500Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La biographie doit être constituée d&apos;au moins 30 caractères.
        /// </summary>
        public static string BioMustBe30Chars {
            get {
                return ResourceManager.GetString("BioMustBe30Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulé.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charte d&apos;utilisation.
        /// </summary>
        public static string CharterUse {
            get {
                return ResourceManager.GetString("CharterUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliquez ici pour ajouter une formation.
        /// </summary>
        public static string ClickHereToAddANewTraining {
            get {
                return ResourceManager.GetString("ClickHereToAddANewTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication.
        /// </summary>
        public static string Communication {
            get {
                return ResourceManager.GetString("Communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brouillon.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Économie / Marketing.
        /// </summary>
        public static string EconomyMarketing {
            get {
                return ResourceManager.GetString("EconomyMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition de la formation.
        /// </summary>
        public static string EditTraining {
            get {
                return ResourceManager.GetString("EditTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un email est requis.
        /// </summary>
        public static string EmailIsRequired {
            get {
                return ResourceManager.GetString("EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salarié-es en entreprise et / ou indépendant-es.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce champs est requis.
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Champs qui apparaîtront dans le catalogue public.
        /// </summary>
        public static string FieldsThatWillAppearInThePublicCatalog {
            get {
                return ResourceManager.GetString("FieldsThatWillAppearInThePublicCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soin aux personnes.
        /// </summary>
        public static string HealthCare {
            get {
                return ResourceManager.GetString("HealthCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonjour.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technologie de l&apos;information.
        /// </summary>
        public static string InformationTechnology {
            get {
                return ResourceManager.GetString("InformationTechnology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email invalide.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;agit-il d&apos;une formation.
        /// </summary>
        public static string IsItATraining {
            get {
                return ResourceManager.GetString("IsItATraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La formation est-elle fournie par Smart ?.
        /// </summary>
        public static string IsTrainingGivenBySmart {
            get {
                return ResourceManager.GetString("IsTrainingGivenBySmart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cours de langue.
        /// </summary>
        public static string LanguageCourse {
            get {
                return ResourceManager.GetString("LanguageCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ullamcorper odio id iaculis lacinia. Aenean iaculis sit amet dolor non interdum. Ut odio odio, vulputate non urna a, consequat facilisis arcu. Pellentesque venenatis ex varius blandit vulputate. Donec maximus commodo mi, at convallis metus tempus vitae. Phasellus malesuada, massa sed dictum tristique, odio tellus blandit ante, eget efficitur diam massa sed dolor. Sed rutrum magna ut urna maximus, vel consectetur urna tempus. Integer tellus ipsum [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LoremIpsum {
            get {
                return ResourceManager.GetString("LoremIpsum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        public static string Marketing {
            get {
                return ResourceManager.GetString("Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum 1000 caractères.
        /// </summary>
        public static string Max1000Characters {
            get {
                return ResourceManager.GetString("Max1000Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum 500 caractères.
        /// </summary>
        public static string Max500Characters {
            get {
                return ResourceManager.GetString("Max500Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deux choix maximum possibles.
        /// </summary>
        public static string MaximumTwoChoices {
            get {
                return ResourceManager.GetString("MaximumTwoChoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Méthodologie.
        /// </summary>
        public static string Methodology {
            get {
                return ResourceManager.GetString("Methodology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 30 caractères.
        /// </summary>
        public static string Min30Char {
            get {
                return ResourceManager.GetString("Min30Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum 30 caractères.
        /// </summary>
        public static string Min30Characters {
            get {
                return ResourceManager.GetString("Min30Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min 30 caractères / max 1000 caractères.
        /// </summary>
        public static string Min30CharMax1000Char {
            get {
                return ResourceManager.GetString("Min30CharMax1000Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to min 30 caractères / max 500 caractères.
        /// </summary>
        public static string Min30CharMax500Char {
            get {
                return ResourceManager.GetString("Min30CharMax500Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon profil formateur.
        /// </summary>
        public static string MyTrainerProfile {
            get {
                return ResourceManager.GetString("MyTrainerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mes formations.
        /// </summary>
        public static string MyTrainings {
            get {
                return ResourceManager.GetString("MyTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon espace utilisateur.
        /// </summary>
        public static string MyUserSpace {
            get {
                return ResourceManager.GetString("MyUserSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivant.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aucune formation trouvée.
        /// </summary>
        public static string NoTrainingFound {
            get {
                return ResourceManager.GetString("NoTrainingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autre.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette page n&apos;existe pas.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En attente de validation.
        /// </summary>
        public static string PendingValidation {
            get {
                return ResourceManager.GetString("PendingValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site personnel.
        /// </summary>
        public static string PersonalWebsite {
            get {
                return ResourceManager.GetString("PersonalWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez sélectionner au moins une option.
        /// </summary>
        public static string PleaseSelectOneOption {
            get {
                return ResourceManager.GetString("PleaseSelectOneOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalités pratiques de la formation.
        /// </summary>
        public static string PracticalModalities {
            get {
                return ResourceManager.GetString("PracticalModalities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Précédent.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biographie.
        /// </summary>
        public static string Profile_bioLabel {
            get {
                return ResourceManager.GetString("Profile_bioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Déposer votre photo pour la téléverser.
        /// </summary>
        public static string Profile_DragDropPicture {
            get {
                return ResourceManager.GetString("Profile_DragDropPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre photo de profil.
        /// </summary>
        public static string Profile_ImageTitle {
            get {
                return ResourceManager.GetString("Profile_ImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner une photo.
        /// </summary>
        public static string Profile_UploadPicture {
            get {
                return ResourceManager.GetString("Profile_UploadPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition de votre profil.
        /// </summary>
        public static string ProfileEdition {
            get {
                return ResourceManager.GetString("ProfileEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier est trop volumineux.
        /// </summary>
        public static string ProfilePage_Image_FileTooBig {
            get {
                return ResourceManager.GetString("ProfilePage_Image_FileTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le fichier est du mauvais type.
        /// </summary>
        public static string ProfilePage_Image_WrongFileType {
            get {
                return ResourceManager.GetString("ProfilePage_Image_WrongFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profil mis à jour.
        /// </summary>
        public static string ProfileUpdatedWithSuccess {
            get {
                return ResourceManager.GetString("ProfileUpdatedWithSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publier.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publié.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refusé.
        /// </summary>
        public static string Refused {
            get {
                return ResourceManager.GetString("Refused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matière scolaire / universitaire.
        /// </summary>
        public static string School {
            get {
                return ResourceManager.GetString("School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to est un enseignement de matières scolaires / assimilées.
        /// </summary>
        public static string SchoolCourse {
            get {
                return ResourceManager.GetString("SchoolCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechercher.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secteurs.
        /// </summary>
        public static string Sectors {
            get {
                return ResourceManager.GetString("Sectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veuillez selectionner au moins un public cible.
        /// </summary>
        public static string SelectOneTrainingTargetAudience {
            get {
                return ResourceManager.GetString("SelectOneTrainingTargetAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Se déconnecter.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réseaux sociaux.
        /// </summary>
        public static string SocialNetworks {
            get {
                return ResourceManager.GetString("SocialNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sciences humaines et sociales.
        /// </summary>
        public static string SocialScience {
            get {
                return ResourceManager.GetString("SocialScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désolé.
        /// </summary>
        public static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spécifiez.
        /// </summary>
        public static string Specify {
            get {
                return ResourceManager.GetString("Specify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        public static string Sport {
            get {
                return ResourceManager.GetString("Sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Étudiant-es / Élève(s).
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seul un super-utilisateur est autorisé à marquer une formation comme étant dispensée par Smart .
        /// </summary>
        public static string SuperUserPermissionToSetSmartTrainingType {
            get {
                return ResourceManager.GetString("SuperUserPermissionToSetSmartTrainingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La formation.
        /// </summary>
        public static string TheTraining {
            get {
                return ResourceManager.GetString("TheTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matière(s).
        /// </summary>
        public static string Topics {
            get {
                return ResourceManager.GetString("Topics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le formateur n&apos;a pas été trouvé.
        /// </summary>
        public static string TrainerNotFound_TrainerId {
            get {
                return ResourceManager.GetString("TrainerNotFound_TrainerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo de profil.
        /// </summary>
        public static string TrainerPicture {
            get {
                return ResourceManager.GetString("TrainerPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fonction.
        /// </summary>
        public static string TrainerTitle {
            get {
                return ResourceManager.GetString("TrainerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collective.
        /// </summary>
        public static string Training_Collective {
            get {
                return ResourceManager.GetString("Training_Collective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Présentation de la formation.
        /// </summary>
        public static string Training_DescriptionLabel {
            get {
                return ResourceManager.GetString("Training_DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collective.
        /// </summary>
        public static string Training_Group {
            get {
                return ResourceManager.GetString("Training_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en groupe.
        /// </summary>
        public static string Training_InGroup {
            get {
                return ResourceManager.GetString("Training_InGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S&apos;agit-il d&apos;une formation ?.
        /// </summary>
        public static string Training_IsItATrainingThat {
            get {
                return ResourceManager.GetString("Training_IsItATrainingThat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to est un cours de langue.
        /// </summary>
        public static string Training_IsLanguageCourse {
            get {
                return ResourceManager.GetString("Training_IsLanguageCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autre.
        /// </summary>
        public static string Training_IsOther {
            get {
                return ResourceManager.GetString("Training_IsOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entre dans le cadre de l&apos;Éducation permanente.
        /// </summary>
        public static string Training_IsPermanentEducation {
            get {
                return ResourceManager.GetString("Training_IsPermanentEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to est professionelle / professionalisante.
        /// </summary>
        public static string Training_IsProfessional {
            get {
                return ResourceManager.GetString("Training_IsProfessional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to est un enseignement de matières scolaires / assimilées.
        /// </summary>
        public static string Training_IsScholarTraining {
            get {
                return ResourceManager.GetString("Training_IsScholarTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individuelle.
        /// </summary>
        public static string Training_Single {
            get {
                return ResourceManager.GetString("Training_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La formation n&apos;existe pas.
        /// </summary>
        public static string TrainingDoesNotExist {
            get {
                return ResourceManager.GetString("TrainingDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectif et contenu de la formation.
        /// </summary>
        public static string TrainingGoal {
            get {
                return ResourceManager.GetString("TrainingGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Présentation de la formation.
        /// </summary>
        public static string TrainingPresentation {
            get {
                return ResourceManager.GetString("TrainingPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formations.
        /// </summary>
        public static string Trainings {
            get {
                return ResourceManager.GetString("Trainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Édition de formations.
        /// </summary>
        public static string TrainingSearchTitle {
            get {
                return ResourceManager.GetString("TrainingSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public cible.
        /// </summary>
        public static string TrainingTarget {
            get {
                return ResourceManager.GetString("TrainingTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre de la formation.
        /// </summary>
        public static string TrainingTitleCreationLabel {
            get {
                return ResourceManager.GetString("TrainingTitleCreationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un titre de formation est requis.
        /// </summary>
        public static string TrainingTitleIsRequired {
            get {
                return ResourceManager.GetString("TrainingTitleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justification de la réduction de la TVA.
        /// </summary>
        public static string TrainingVatJustification {
            get {
                return ResourceManager.GetString("TrainingVatJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demandeur-euse d&apos;emploi.
        /// </summary>
        public static string Unemployed {
            get {
                return ResourceManager.GetString("Unemployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous ne pouvez pas éditer une formation dont vous n&apos;êtes pas l&apos;auteur..
        /// </summary>
        public static string UpdateTraining_YouCantEditATrainingYouDidntCreate {
            get {
                return ResourceManager.GetString("UpdateTraining_YouCantEditATrainingYouDidntCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string UrlSitePublic {
            get {
                return ResourceManager.GetString("UrlSitePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to J&apos;accepte.
        /// </summary>
        public static string UserChartAccept {
            get {
                return ResourceManager.GetString("UserChartAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous êtes sur le point de supprimer la formation.
        /// </summary>
        public static string YouAreAboutToDeleteTraining {
            get {
                return ResourceManager.GetString("YouAreAboutToDeleteTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous n&apos;avez aucune formation.
        /// </summary>
        public static string YouDontHaveAnyTrainings {
            get {
                return ResourceManager.GetString("YouDontHaveAnyTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous devez selectionner au moins une matière.
        /// </summary>
        public static string YouMustSelectedAtLeastOneTopic {
            get {
                return ResourceManager.GetString("YouMustSelectedAtLeastOneTopic", resourceCulture);
            }
        }
    }
}
