//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart.FA.Catalog.Localization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CatalogResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CatalogResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Smart.FA.Catalog.Localization.CatalogResources", typeof(CatalogResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encoder une formation.
        /// </summary>
        public static string AddNewTraining {
            get {
                return ResourceManager.GetString("AddNewTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Charte d&apos;utilisation.
        /// </summary>
        public static string AdminHomepage_AcceptCharter {
            get {
                return ResourceManager.GetString("AdminHomepage_AcceptCharter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La charte d&apos;utilisateur de Formateurs Associés n&apos;a pas été acceptée.
        /// </summary>
        public static string AdminHomePage_HasNotAcceptedUserChart {
            get {
                return ResourceManager.GetString("AdminHomePage_HasNotAcceptedUserChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Je m&apos;engage à respecter la Charter d&apos;utilisation de Formateurs Associés.
        /// </summary>
        public static string AdminHomepage_IAcceptCharter {
            get {
                return ResourceManager.GetString("AdminHomepage_IAcceptCharter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  est un catalogue des formations organisées et produites par Smart au travers des entités Formateurs Associés asbl et accessoirement Productions Associées asbl. C&apos;est un outil en ligne mis à votre disposition gratuitement et sans publicité..
        /// </summary>
        public static string AdminHomepage_IntroductionPart1 {
            get {
                return ResourceManager.GetString("AdminHomepage_IntroductionPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous êtes invité·es à y compléter  votre fiche de profil, puis à y encoder les formations que vous proposez..
        /// </summary>
        public static string AdminHomepage_IntroductionPart2 {
            get {
                return ResourceManager.GetString("AdminHomepage_IntroductionPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les informations ainsi encodées seront visibles publiquement sur le site vitrine .
        /// </summary>
        public static string AdminHomepage_IntroductionPart3 {
            get {
                return ResourceManager.GetString("AdminHomepage_IntroductionPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lire la charte utilisateur.
        /// </summary>
        public static string AdminHomePage_UserChart {
            get {
                return ResourceManager.GetString("AdminHomePage_UserChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Interface d&apos;encodage de formations.
        /// </summary>
        public static string AdminHomepage_WhatIsFormateurAssocieTitle {
            get {
                return ResourceManager.GetString("AdminHomepage_WhatIsFormateurAssocieTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Compléter votre profil.
        /// </summary>
        public static string AdminHomepageProfil_Button {
            get {
                return ResourceManager.GetString("AdminHomepageProfil_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous ne disposez que d’une seule fiche profil par titulaire..
        /// </summary>
        public static string AdminHomepageProfil_IntroductionPart1 {
            get {
                return ResourceManager.GetString("AdminHomepageProfil_IntroductionPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les champs nom et prénom sont obligatoires (et identiques à votre fiche d’inscription Smart). Le champ biographie ainsi que les champs « réseaux sociaux » ne sont pas obligatoires. Un formulaire de contact est par ailleurs mis en place pour permettre aux internautes de vous contacter directement. Ce formulaire est lié à l’adresse mail renseignée dans la fiche d’inscription, l’adresse mail n’apparaît jamais directement. .
        /// </summary>
        public static string AdminHomepageProfil_IntroductionPart2 {
            get {
                return ResourceManager.GetString("AdminHomepageProfil_IntroductionPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Profil  .
        /// </summary>
        public static string AdminHomepageProfil_Title {
            get {
                return ResourceManager.GetString("AdminHomepageProfil_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Encoder une formation.
        /// </summary>
        public static string AdminHomepageTraining_Button {
            get {
                return ResourceManager.GetString("AdminHomepageTraining_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous pouvez encoder autant de formations que vous le souhaitez.  .
        /// </summary>
        public static string AdminHomepageTraining_IntroductionPart1 {
            get {
                return ResourceManager.GetString("AdminHomepageTraining_IntroductionPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous pouvez sauvegarder une fiche formation en cours de rédaction pour y revenir plus tard avant de la publier. Vous pouvez également dépublier une fiche ou la supprimer.  .
        /// </summary>
        public static string AdminHomepageTraining_IntroductionPart2 {
            get {
                return ResourceManager.GetString("AdminHomepageTraining_IntroductionPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nous vous invitons à veiller régulièrement à la mise à jour de vos contenus. .
        /// </summary>
        public static string AdminHomepageTraining_IntroductionPart3 {
            get {
                return ResourceManager.GetString("AdminHomepageTraining_IntroductionPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Formation.
        /// </summary>
        public static string AdminHomepageTraining_Title {
            get {
                return ResourceManager.GetString("AdminHomepageTraining_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Avant d’encoder des formations, vous devez confirmer avoir lu et accepté les conditions énoncées dans la charte d’utilisation du site learning.smart.coop. Cette charte est également disponible à la consultation dans votre Espace Activité.   .
        /// </summary>
        public static string AdminUserChart_IntroductionPart1 {
            get {
                return ResourceManager.GetString("AdminUserChart_IntroductionPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur s&apos;est déroulée durant la recherche. Veuillez essayer à nouveau.
        /// </summary>
        public static string AnErrorOccurredWhileSearching {
            get {
                return ResourceManager.GetString("AnErrorOccurredWhileSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Êtes vous sûr-e ?.
        /// </summary>
        public static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La biographie ne peut excéder 500 caractères.
        /// </summary>
        public static string BioCannotExceed500Chars {
            get {
                return ResourceManager.GetString("BioCannotExceed500Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La biographie doit être constituée d&apos;au moins 30 caractères.
        /// </summary>
        public static string BioMustBe30Chars {
            get {
                return ResourceManager.GetString("BioMustBe30Chars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annuler.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Annulé.
        /// </summary>
        public static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Charte d&apos;utilisation.
        /// </summary>
        public static string CharterUse {
            get {
                return ResourceManager.GetString("CharterUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cliquez ici pour ajouter une formation.
        /// </summary>
        public static string ClickHereToAddANewTraining {
            get {
                return ResourceManager.GetString("ClickHereToAddANewTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Communication.
        /// </summary>
        public static string Communication {
            get {
                return ResourceManager.GetString("Communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Brouillon.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Économie / Marketing.
        /// </summary>
        public static string EconomyMarketing {
            get {
                return ResourceManager.GetString("EconomyMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Édition de la formation : .
        /// </summary>
        public static string EditTraining {
            get {
                return ResourceManager.GetString("EditTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un email est requis.
        /// </summary>
        public static string EmailIsRequired {
            get {
                return ResourceManager.GetString("EmailIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Salarié-es en entreprise et / ou indépendant-es.
        /// </summary>
        public static string Employee {
            get {
                return ResourceManager.GetString("Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce champ est requis.
        /// </summary>
        public static string FieldRequired {
            get {
                return ResourceManager.GetString("FieldRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Champs qui apparaîtront dans le catalogue public.
        /// </summary>
        public static string FieldsThatWillAppearInThePublicCatalog {
            get {
                return ResourceManager.GetString("FieldsThatWillAppearInThePublicCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Retour à l&apos;accueil.
        /// </summary>
        public static string GoBackHome {
            get {
                return ResourceManager.GetString("GoBackHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Soin aux personnes.
        /// </summary>
        public static string HealthCare {
            get {
                return ResourceManager.GetString("HealthCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bonjour.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Technologie de l&apos;information.
        /// </summary>
        public static string InformationTechnology {
            get {
                return ResourceManager.GetString("InformationTechnology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email invalide.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S&apos;agit-il d&apos;une formation.
        /// </summary>
        public static string IsItATraining {
            get {
                return ResourceManager.GetString("IsItATraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La formation est-elle fournie par Smart ?.
        /// </summary>
        public static string IsTrainingGivenBySmart {
            get {
                return ResourceManager.GetString("IsTrainingGivenBySmart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cours de langue.
        /// </summary>
        public static string LanguageCourse {
            get {
                return ResourceManager.GetString("LanguageCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ullamcorper odio id iaculis lacinia. Aenean iaculis sit amet dolor non interdum. Ut odio odio, vulputate non urna a, consequat facilisis arcu. Pellentesque venenatis ex varius blandit vulputate. Donec maximus commodo mi, at convallis metus tempus vitae. Phasellus malesuada, massa sed dictum tristique, odio tellus blandit ante, eget efficitur diam massa sed dolor. Sed rutrum magna ut urna maximus, vel consectetur urna tempus. Integer tellus ipsum [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string LoremIpsum {
            get {
                return ResourceManager.GetString("LoremIpsum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Marketing.
        /// </summary>
        public static string Marketing {
            get {
                return ResourceManager.GetString("Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum 1000 caractères.
        /// </summary>
        public static string Max1000Characters {
            get {
                return ResourceManager.GetString("Max1000Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Maximum 500 caractères.
        /// </summary>
        public static string Max500Characters {
            get {
                return ResourceManager.GetString("Max500Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deux choix maximum possibles.
        /// </summary>
        public static string MaximumTwoChoices {
            get {
                return ResourceManager.GetString("MaximumTwoChoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Méthodologie.
        /// </summary>
        public static string Methodology {
            get {
                return ResourceManager.GetString("Methodology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Minimum 30 caractères.
        /// </summary>
        public static string Min30Char {
            get {
                return ResourceManager.GetString("Min30Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Minimum 30 caractères.
        /// </summary>
        public static string Min30Characters {
            get {
                return ResourceManager.GetString("Min30Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à min 30 caractères / max 1000 caractères.
        /// </summary>
        public static string Min30CharMax1000Char {
            get {
                return ResourceManager.GetString("Min30CharMax1000Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à min 30 caractères / max 500 caractères.
        /// </summary>
        public static string Min30CharMax500Char {
            get {
                return ResourceManager.GetString("Min30CharMax500Char", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mon profil .
        /// </summary>
        public static string MyTrainerProfile {
            get {
                return ResourceManager.GetString("MyTrainerProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mes formations.
        /// </summary>
        public static string MyTrainings {
            get {
                return ResourceManager.GetString("MyTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mon espace utilisateur.
        /// </summary>
        public static string MyUserSpace {
            get {
                return ResourceManager.GetString("MyUserSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suivant.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucune formation trouvée.
        /// </summary>
        public static string NoTrainingFound {
            get {
                return ResourceManager.GetString("NoTrainingFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Autre.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cette page n&apos;existe pas.
        /// </summary>
        public static string PageNotFound {
            get {
                return ResourceManager.GetString("PageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à En attente de validation.
        /// </summary>
        public static string PendingValidation {
            get {
                return ResourceManager.GetString("PendingValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Site personnel.
        /// </summary>
        public static string PersonalWebsite {
            get {
                return ResourceManager.GetString("PersonalWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez sélectionner au moins une option.
        /// </summary>
        public static string PleaseSelectOneOption {
            get {
                return ResourceManager.GetString("PleaseSelectOneOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modalités pratiques de la formation.
        /// </summary>
        public static string PracticalModalities {
            get {
                return ResourceManager.GetString("PracticalModalities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Précédent.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Biographie.
        /// </summary>
        public static string Profile_bioLabel {
            get {
                return ResourceManager.GetString("Profile_bioLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Déposer votre photo pour la téléverser.
        /// </summary>
        public static string Profile_DragDropPicture {
            get {
                return ResourceManager.GetString("Profile_DragDropPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Votre photo de profil.
        /// </summary>
        public static string Profile_ImageTitle {
            get {
                return ResourceManager.GetString("Profile_ImageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sélectionner une photo.
        /// </summary>
        public static string Profile_UploadPicture {
            get {
                return ResourceManager.GetString("Profile_UploadPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Édition de votre profil.
        /// </summary>
        public static string ProfileEdition {
            get {
                return ResourceManager.GetString("ProfileEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier est trop volumineux.
        /// </summary>
        public static string ProfilePage_Image_FileTooBig {
            get {
                return ResourceManager.GetString("ProfilePage_Image_FileTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier est du mauvais type.
        /// </summary>
        public static string ProfilePage_Image_WrongFileType {
            get {
                return ResourceManager.GetString("ProfilePage_Image_WrongFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Profil mis à jour.
        /// </summary>
        public static string ProfileUpdatedWithSuccess {
            get {
                return ResourceManager.GetString("ProfileUpdatedWithSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publier.
        /// </summary>
        public static string Publish {
            get {
                return ResourceManager.GetString("Publish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Publié.
        /// </summary>
        public static string Published {
            get {
                return ResourceManager.GetString("Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refusé.
        /// </summary>
        public static string Refused {
            get {
                return ResourceManager.GetString("Refused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarder.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Matière scolaire / universitaire.
        /// </summary>
        public static string School {
            get {
                return ResourceManager.GetString("School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à est un enseignement de matières scolaires / assimilées.
        /// </summary>
        public static string SchoolCourse {
            get {
                return ResourceManager.GetString("SchoolCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rechercher.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Secteurs.
        /// </summary>
        public static string Sectors {
            get {
                return ResourceManager.GetString("Sectors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Veuillez selectionner au moins un public cible.
        /// </summary>
        public static string SelectOneTrainingTargetAudience {
            get {
                return ResourceManager.GetString("SelectOneTrainingTargetAudience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Déconnexion.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Réseaux sociaux.
        /// </summary>
        public static string SocialNetworks {
            get {
                return ResourceManager.GetString("SocialNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sciences humaines et sociales.
        /// </summary>
        public static string SocialScience {
            get {
                return ResourceManager.GetString("SocialScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Désolé.
        /// </summary>
        public static string Sorry {
            get {
                return ResourceManager.GetString("Sorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Spécifiez.
        /// </summary>
        public static string Specify {
            get {
                return ResourceManager.GetString("Specify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sport.
        /// </summary>
        public static string Sport {
            get {
                return ResourceManager.GetString("Sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Étudiant-es / Élève(s).
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Seul un super-utilisateur est autorisé à marquer une formation comme étant dispensée par Smart .
        /// </summary>
        public static string SuperUserPermissionToSetSmartTrainingType {
            get {
                return ResourceManager.GetString("SuperUserPermissionToSetSmartTrainingType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La formation.
        /// </summary>
        public static string TheTraining {
            get {
                return ResourceManager.GetString("TheTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Matière(s).
        /// </summary>
        public static string Topics {
            get {
                return ResourceManager.GetString("Topics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le formateur n&apos;a pas été trouvé.
        /// </summary>
        public static string TrainerNotFound_TrainerId {
            get {
                return ResourceManager.GetString("TrainerNotFound_TrainerId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Photo de profil.
        /// </summary>
        public static string TrainerPicture {
            get {
                return ResourceManager.GetString("TrainerPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fonction.
        /// </summary>
        public static string TrainerTitle {
            get {
                return ResourceManager.GetString("TrainerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collective.
        /// </summary>
        public static string Training_Collective {
            get {
                return ResourceManager.GetString("Training_Collective", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Présentation de la formation.
        /// </summary>
        public static string Training_DescriptionLabel {
            get {
                return ResourceManager.GetString("Training_DescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Collective.
        /// </summary>
        public static string Training_Group {
            get {
                return ResourceManager.GetString("Training_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à en groupe.
        /// </summary>
        public static string Training_InGroup {
            get {
                return ResourceManager.GetString("Training_InGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à S&apos;agit-il d&apos;une formation ?.
        /// </summary>
        public static string Training_IsItATrainingThat {
            get {
                return ResourceManager.GetString("Training_IsItATrainingThat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à est un cours de langue.
        /// </summary>
        public static string Training_IsLanguageCourse {
            get {
                return ResourceManager.GetString("Training_IsLanguageCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Autre.
        /// </summary>
        public static string Training_IsOther {
            get {
                return ResourceManager.GetString("Training_IsOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à entre dans le cadre de l&apos;Éducation permanente.
        /// </summary>
        public static string Training_IsPermanentEducation {
            get {
                return ResourceManager.GetString("Training_IsPermanentEducation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à est professionelle / professionnalisante.
        /// </summary>
        public static string Training_IsProfessional {
            get {
                return ResourceManager.GetString("Training_IsProfessional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à est un enseignement de matières scolaires / assimilées.
        /// </summary>
        public static string Training_IsScholarTraining {
            get {
                return ResourceManager.GetString("Training_IsScholarTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Individuelle.
        /// </summary>
        public static string Training_Single {
            get {
                return ResourceManager.GetString("Training_Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Formation créée avec succès.
        /// </summary>
        public static string TrainingCreatedWithSuccess {
            get {
                return ResourceManager.GetString("TrainingCreatedWithSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Formation supprimée avec succès.
        /// </summary>
        public static string TrainingDeletedWithSuccess {
            get {
                return ResourceManager.GetString("TrainingDeletedWithSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La formation n&apos;existe pas.
        /// </summary>
        public static string TrainingDoesNotExist {
            get {
                return ResourceManager.GetString("TrainingDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Formation éditée avec succès.
        /// </summary>
        public static string TrainingEditedWithSuccess {
            get {
                return ResourceManager.GetString("TrainingEditedWithSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Objectif et contenu de la formation.
        /// </summary>
        public static string TrainingGoal {
            get {
                return ResourceManager.GetString("TrainingGoal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Présentation de la formation.
        /// </summary>
        public static string TrainingPresentation {
            get {
                return ResourceManager.GetString("TrainingPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Formations.
        /// </summary>
        public static string Trainings {
            get {
                return ResourceManager.GetString("Trainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Édition de formations.
        /// </summary>
        public static string TrainingSearchTitle {
            get {
                return ResourceManager.GetString("TrainingSearchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Public cible.
        /// </summary>
        public static string TrainingTarget {
            get {
                return ResourceManager.GetString("TrainingTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Titre de la formation.
        /// </summary>
        public static string TrainingTitleCreationLabel {
            get {
                return ResourceManager.GetString("TrainingTitleCreationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Un titre de formation est requis.
        /// </summary>
        public static string TrainingTitleIsRequired {
            get {
                return ResourceManager.GetString("TrainingTitleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Justification de la réduction de la TVA.
        /// </summary>
        public static string TrainingVatJustification {
            get {
                return ResourceManager.GetString("TrainingVatJustification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Demandeur-euse d&apos;emploi.
        /// </summary>
        public static string Unemployed {
            get {
                return ResourceManager.GetString("Unemployed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur innattendue s&apos;est produite.
        /// </summary>
        public static string UnExpectedError {
            get {
                return ResourceManager.GetString("UnExpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous ne pouvez pas éditer une formation dont vous n&apos;êtes pas l&apos;auteur..
        /// </summary>
        public static string UpdateTraining_YouCantEditATrainingYouDidntCreate {
            get {
                return ResourceManager.GetString("UpdateTraining_YouCantEditATrainingYouDidntCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à learning.smart.coop.
        /// </summary>
        public static string UrlSitePublic {
            get {
                return ResourceManager.GetString("UrlSitePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à J&apos;accepte.
        /// </summary>
        public static string UserChartAccept {
            get {
                return ResourceManager.GetString("UserChartAccept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous êtes sur le point de supprimer la formation.
        /// </summary>
        public static string YouAreAboutToDeleteTraining {
            get {
                return ResourceManager.GetString("YouAreAboutToDeleteTraining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous n&apos;avez aucune formation.
        /// </summary>
        public static string YouDontHaveAnyTrainings {
            get {
                return ResourceManager.GetString("YouDontHaveAnyTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vous devez selectionner au moins une matière.
        /// </summary>
        public static string YouMustSelectedAtLeastOneTopic {
            get {
                return ResourceManager.GetString("YouMustSelectedAtLeastOneTopic", resourceCulture);
            }
        }
    }
}
