// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Smart.FA.Catalog.Showcase.Domain.Models
{
    public partial class TrainerList : IHasId
    {
    }
}
