version: "3.9"

services:
  datasource:
    build:
      context: .
      dockerfile: DB.Dockerfile
    hostname: "${DOCKER_NAME}-datasource"
    container_name: "${DOCKER_NAME}-datasource"
    restart: always
    ports:
      - "1433:1433"
    environment:
      - "SA_PASSWORD=TheLocalStoragePassword!"
    networks:
      - "cfa"
  api:
    depends_on:
      - datasource
    build:
      context: .
      dockerfile: Web.Dockerfile
    hostname: ${DOCKER_NAME}-api
    container_name: ${DOCKER_NAME}-api
    restart: always
    ports:
      - "5000:80"
    networks:
      - "cfa"
    environment:
      - "ASPNETCORE_ENVIRONMENT=${DOCKER_ENVIRONMENT}"
    command:
      /opt/mssql/bin/sqlservr --accept-eula & sleep 70 \
      && /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'localStoragePassword!' \
      && pkill sqlservr
networks:
  cfa:
    name: cfa
    ipam:
      driver: default
      config:
        - subnet: 172.21.1.0/24
          gateway: 172.21.1.1
