//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart.FA.Catalog.Showcase.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ShowcaseResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ShowcaseResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Smart.FA.Catalog.Showcase.Localization.ShowcaseResources", typeof(ShowcaseResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tous les formateur·trices.
        /// </summary>
        public static string AllTrainers {
            get {
                return ResourceManager.GetString("AllTrainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toutes les formations.
        /// </summary>
        public static string AllTrainings {
            get {
                return ResourceManager.GetString("AllTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formateurs Associés.
        /// </summary>
        public static string AssociateTrainers {
            get {
                return ResourceManager.GetString("AssociateTrainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Votre message a bien été envoyé..
        /// </summary>
        public static string Contact_ConfirmationMessage {
            get {
                return ResourceManager.GetString("Contact_ConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nom@site.com.
        /// </summary>
        public static string Contact_DefaultEmail {
            get {
                return ResourceManager.GetString("Contact_DefaultEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benoit Dupont.
        /// </summary>
        public static string Contact_DefaultName {
            get {
                return ResourceManager.GetString("Contact_DefaultName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un problème est survenu. L&apos;envoi du message a échoué..
        /// </summary>
        public static string Contact_ErrorMessage {
            get {
                return ResourceManager.GetString("Contact_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresse email.
        /// </summary>
        public static string Contact_LabelEmail {
            get {
                return ResourceManager.GetString("Contact_LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Contact_LabelMessage {
            get {
                return ResourceManager.GetString("Contact_LabelMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prénom et Nom.
        /// </summary>
        public static string Contact_LabelName {
            get {
                return ResourceManager.GetString("Contact_LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envoyer.
        /// </summary>
        public static string Contact_LabelSend {
            get {
                return ResourceManager.GetString("Contact_LabelSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous avez des questions en lien avec la formation chez Smart, n’hésitez pas à nous contacter via le formulaire ci-dessous..
        /// </summary>
        public static string Contact_Presentation {
            get {
                return ResourceManager.GetString("Contact_Presentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://smartbe.be.
        /// </summary>
        public static string Contact_Presentation_Link {
            get {
                return ResourceManager.GetString("Contact_Presentation_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour toute autre question concernant Smart, rendez-vous sur notre site.
        /// </summary>
        public static string Contact_Presentation_SecondPart {
            get {
                return ResourceManager.GetString("Contact_Presentation_SecondPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacter Formateurs Associés.
        /// </summary>
        public static string Contact_TitlePage {
            get {
                return ResourceManager.GetString("Contact_TitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Footer_LabelContact {
            get {
                return ResourceManager.GetString("Footer_LabelContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivre.
        /// </summary>
        public static string Footer_LabelFollow {
            get {
                return ResourceManager.GetString("Footer_LabelFollow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentions Légales.
        /// </summary>
        public static string Footer_LabelLegalNotice {
            get {
                return ResourceManager.GetString("Footer_LabelLegalNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nos sites.
        /// </summary>
        public static string Footer_LabelOurWebsites {
            get {
                return ResourceManager.GetString("Footer_LabelOurWebsites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accès rapides.
        /// </summary>
        public static string Footer_LabelQuickLinks {
            get {
                return ResourceManager.GetString("Footer_LabelQuickLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RGPD / Confidentialité.
        /// </summary>
        public static string Footer_LabelRGPD {
            get {
                return ResourceManager.GetString("Footer_LabelRGPD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cette page n&apos;existe pas.
        /// </summary>
        public static string GenericNotFoundPageMessage {
            get {
                return ResourceManager.GetString("GenericNotFoundPageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Désolé.
        /// </summary>
        public static string GenericNotFoundPageTitle {
            get {
                return ResourceManager.GetString("GenericNotFoundPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formateurs Associés.
        /// </summary>
        public static string Header_LabelFA {
            get {
                return ResourceManager.GetString("Header_LabelFA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &gt;&gt; Accès membre &lt;&lt;.
        /// </summary>
        public static string Header_LabelMemberAccess {
            get {
                return ResourceManager.GetString("Header_LabelMemberAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formateurs.
        /// </summary>
        public static string Header_LabelTrainers {
            get {
                return ResourceManager.GetString("Header_LabelTrainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formations.
        /// </summary>
        public static string Header_LabelTrainings {
            get {
                return ResourceManager.GetString("Header_LabelTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bienvenue dans le monde de la formation de Smart, .
        /// </summary>
        public static string Homepage_IntroductionPart1 {
            get {
                return ResourceManager.GetString("Homepage_IntroductionPart1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart est une coopérative de travailleuses et travailleurs qui utilisent sa structure pour exercer leur métier, par exemple de la formation..
        /// </summary>
        public static string Homepage_IntroductionPart2 {
            get {
                return ResourceManager.GetString("Homepage_IntroductionPart2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ce catalogue en ligne s’adresse à toute personne en recherche d’une formation. Vous trouverez sur ce site des formations de type scolaire, professionnel  (organisées et produites par Formateurs Associés asbl et Productions Associées asbl, le cas échéant) ou encore récréatif (uniquement dans Producteurs Associés asbl). Vous visualisez aisément la personne qui dispense la formation et pouvez la contacter en direct pour obtenir davantage d’informations. .
        /// </summary>
        public static string Homepage_IntroductionPart3 {
            get {
                return ResourceManager.GetString("Homepage_IntroductionPart3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aperçu des formations .
        /// </summary>
        public static string Homepage_Subtitle {
            get {
                return ResourceManager.GetString("Homepage_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to À propos.
        /// </summary>
        public static string Homepage_Title {
            get {
                return ResourceManager.GetString("Homepage_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de formateur·trices :.
        /// </summary>
        public static string Homepage_TrainersCount {
            get {
                return ResourceManager.GetString("Homepage_TrainersCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre de formations :.
        /// </summary>
        public static string Homepage_TrainingCount {
            get {
                return ResourceManager.GetString("Homepage_TrainingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mentions Légales.
        /// </summary>
        public static string LegalNotice_TitlePage {
            get {
                return ResourceManager.GetString("LegalNotice_TitlePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc mauris elit, commodo sed risus commodo, lobortis tempor augue. Praesent fermentum posuere congue. Curabitur sit amet finibus turpis. Suspendisse venenatis, ante ac tempor venenatis, mauris ipsum rutrum lacus, sit amet pellentesque mi ligula imperdiet urna. Maecenas eget purus tempus, fringilla nibh vel, vestibulum est. Phasellus ut diam nec mauris pharetra condimentum non id enim. Pellentesque facilisis libero in pretium vestibulum. Ut sapien neq [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LoremIpsum {
            get {
                return ResourceManager.GetString("LoremIpsum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suivant.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectifs.
        /// </summary>
        public static string Objectives {
            get {
                return ResourceManager.GetString("Objectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modalités pratiques.
        /// </summary>
        public static string PracticalModalities {
            get {
                return ResourceManager.GetString("PracticalModalities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Présentation.
        /// </summary>
        public static string Presentation {
            get {
                return ResourceManager.GetString("Presentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Précédent.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sous titre.
        /// </summary>
        public static string PublicPage_Subtitle {
            get {
                return ResourceManager.GetString("PublicPage_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formations.
        /// </summary>
        public static string TitteTrainings {
            get {
                return ResourceManager.GetString("TitteTrainings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication.
        /// </summary>
        public static string TopicName_Communication {
            get {
                return ResourceManager.GetString("TopicName_Communication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Art / Culture.
        /// </summary>
        public static string TopicName_Culture {
            get {
                return ResourceManager.GetString("TopicName_Culture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Économie / Marketing.
        /// </summary>
        public static string TopicName_EconomyMarketing {
            get {
                return ResourceManager.GetString("TopicName_EconomyMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soin aux personnes.
        /// </summary>
        public static string TopicName_HealthCare {
            get {
                return ResourceManager.GetString("TopicName_HealthCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technologie de l&apos;information.
        /// </summary>
        public static string TopicName_InformationTechnology {
            get {
                return ResourceManager.GetString("TopicName_InformationTechnology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cours de langue.
        /// </summary>
        public static string TopicName_LanguageCourse {
            get {
                return ResourceManager.GetString("TopicName_LanguageCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing.
        /// </summary>
        public static string TopicName_Marketing {
            get {
                return ResourceManager.GetString("TopicName_Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autre.
        /// </summary>
        public static string TopicName_Other {
            get {
                return ResourceManager.GetString("TopicName_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matière scolaire / universitaire.
        /// </summary>
        public static string TopicName_School {
            get {
                return ResourceManager.GetString("TopicName_School", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sciences humaines et sociales.
        /// </summary>
        public static string TopicName_SocialScience {
            get {
                return ResourceManager.GetString("TopicName_SocialScience", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TopicName_Sport {
            get {
                return ResourceManager.GetString("TopicName_Sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour vers les formations.
        /// </summary>
        public static string ToTrainingHomePage {
            get {
                return ResourceManager.GetString("ToTrainingHomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Les formateur·trices de Formateurs Associés.
        /// </summary>
        public static string TrainersOfAssociateTrainers {
            get {
                return ResourceManager.GetString("TrainersOfAssociateTrainers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formations à suivre.
        /// </summary>
        public static string TrainingsToFollow {
            get {
                return ResourceManager.GetString("TrainingsToFollow", resourceCulture);
            }
        }
    }
}
