// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable

namespace Smart.FA.Catalog.Showcase.Domain.Models;

public partial class TrainerDetails
{
    public int Id { get; set; }
    public string FirstName { get; set; } = null!;
    public string LastName { get; set; } = null!;
    public string Biography { get; set; } = null!;
    public string Title { get; set; } = null!;
    public int? SocialNetwork { get; set; }
    public string? UrlToProfile { get; set; }
    public string? ProfileImagePath { get; set; }
}
