// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Smart.FA.Catalog.Showcase.Domain.Models
{
    public partial class TrainingDetails
    {
        public int TrainingId { get; set; }
        public string TrainingTitle { get; set; }
        public string TrainingMethodology { get; set; }
        public string TrainingGoal { get; set; }
        public string TrainingPracticalModalities { get; set; }
        public int TrainingTopicId { get; set; }
        public string TrainingLanguage { get; set; }
        public string TrainerFirstName { get; set; }
        public string TrainerLastName { get; set; }
        public string TrainerTitle { get; set; }
        public short TrainingStatusId { get; set; }
    }
}