// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Smart.FA.Catalog.Showcase.Domain.Models
{
    public partial class TrainerDetails
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Biography { get; set; }
        public string Title { get; set; }
        public int? SocialNetwork { get; set; }
        public string UrlToProfile { get; set; }
    }
}
