// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable

namespace Smart.FA.Catalog.Showcase.Domain.Models;
public partial class TrainingList
{
    public int TrainingId { get; set; }
    public string Title { get; set; }
    public string Language { get; set; }
    public string TrainerFirstName { get; set; }
    public string TrainerLastName { get; set; }
    public int Topic { get; set; }
    public short Status { get; set; }
    public int TrainerId { get; set; }
}
