// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Smart.FA.Catalog.Showcase.Domain.Models
{
    public partial class TrainingList
    {
        public int TrainingId { get; set; }
        public string TrainingTitle { get; set; }
        public string TrainingLanguage { get; set; }
        public string TrainerFirstName { get; set; }
        public string TrainerLastName { get; set; }
        public int TrainingTopic { get; set; }
        public short TrainingStatus { get; set; }
        public int TrainerId { get; set; }
    }
}