// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Smart.FA.Catalog.Showcase.Domain.Models;

#nullable disable

namespace Smart.FA.Catalog.Showcase.Infrastructure.Data;

public partial class CatalogShowcaseContext : DbContext
{
    public CatalogShowcaseContext(DbContextOptions<CatalogShowcaseContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TrainerDetails> TrainerDetails { get; set; }
    public virtual DbSet<TrainingDetails> TrainingDetails { get; set; }
    public virtual DbSet<TrainingList> TrainingList { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.HasAnnotation("Relational:Collation", "SQL_Latin1_General_CP1_CI_AS");

        modelBuilder.Entity<TrainerDetails>(entity =>
        {
            entity.HasKey(x => new { x.Id, x.SocialNetwork });

            entity.ToView("v_TrainerDetails");

            entity.Property(e => e.Biography)
                .IsRequired()
                .HasMaxLength(1500);

            entity.Property(e => e.FirstName)
                .IsRequired()
                .HasMaxLength(200);

            entity.Property(e => e.LastName)
                .IsRequired()
                .HasMaxLength(200);

            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(150);

            entity.Property(e => e.SocialNetwork).HasColumnName("SocialNetwork");

            entity.Property(e => e.UrlToProfile).HasColumnName("UrlToProfile");
        });

        modelBuilder.Entity<TrainingDetails>(entity =>
        {
            entity.HasKey(x => new { x.Id, x.Language, x.TrainingTopicId });

            entity.ToView("v_TrainingDetails");

            entity.Property(e => e.TrainerFirstName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("FirstName");

            entity.Property(e => e.TrainerLastName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("LastName");

            entity.Property(e => e.Goal)
                .HasMaxLength(1500)
                .HasColumnName("Goal");

            entity.Property(e => e.Id).HasColumnName("Id");

            entity.Property(e => e.Language)
                .IsRequired()
                .HasMaxLength(2)
                .HasColumnName("Language")
                .IsFixedLength(true);

            entity.Property(e => e.Methodology)
                .HasMaxLength(1500)
                .HasColumnName("Methodology"); 

            entity.Property(e => e.PracticalModalities)
                .HasMaxLength(1000)
                .HasColumnName("PracticalModalities");

            entity.Property(e => e.StatusId).HasColumnName("StatusId");

            entity.Property(e => e.TrainingTitle)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("Title");
        });

        modelBuilder.Entity<TrainingList>(entity =>
        {
            entity.HasKey(x => new { x.TrainingId, x.Language, x.Topic });

            entity.ToView("v_TrainingList");

            entity.Property(e => e.TrainerFirstName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("FirstName");

            entity.Property(e => e.TrainerLastName)
                .IsRequired()
                .HasMaxLength(200)
                .HasColumnName("LastName");

            entity.Property(e => e.TrainerId)
                .IsRequired()
                .HasColumnName("trainerId");

            entity.Property(e => e.TrainingId).HasColumnName("Id");

            entity.Property(e => e.Language)
                .IsRequired()
                .HasMaxLength(2)
                .HasColumnName("Language")
                .IsFixedLength(true);

            entity.Property(e => e.Status).HasColumnName("StatusId");

            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("Title");

            entity.Property(e => e.Topic).HasColumnName("TrainingTopicId");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
