//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Smart.FA.Catalog.Web.Resources.Pages.Admin.Trainings.List {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ListModel {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ListModel() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Web.Resources.Pages.Admin.Trainings.List.ListModel", typeof(ListModel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Communication.
        /// </summary>
        internal static string Communication {
            get {
                return ResourceManager.GetString("Communication", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Soin aux personnes.
        /// </summary>
        internal static string Health {
            get {
                return ResourceManager.GetString("Health", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Informatique et technologies.
        /// </summary>
        internal static string InformationTechnology {
            get {
                return ResourceManager.GetString("InformationTechnology", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cours de langue.
        /// </summary>
        internal static string LanguageCourse {
            get {
                return ResourceManager.GetString("LanguageCourse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Matière scolaire / universitaire.
        /// </summary>
        internal static string School {
            get {
                return ResourceManager.GetString("School", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sciences humaines et sociales.
        /// </summary>
        internal static string SocialScience {
            get {
                return ResourceManager.GetString("SocialScience", resourceCulture);
            }
        }
    }
}
